# Generated by Django 3.2.3 on 2021-05-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_courses_api', '0002_auto_20210518_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseparticipant',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
